name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
      # FIXME: run npm ci in parallel on Github action breaks puppeteer with `Could not find Chrome` error. Something to do with the cache?
      # this bug? https://github.com/pa11y/pa11y/issues/824
      - run: npm ci
      - run: npm test
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
